// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: electrum.proto

package org.smartwallet.stratum.protos;

public final class Protos {
  private Protos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ElectrumOrBuilder extends
      // @@protoc_insertion_point(interface_extends:stratum.Electrum)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .stratum.Transaction transactions = 1;</code>
     */
    java.util.List<org.smartwallet.stratum.protos.Protos.Transaction> 
        getTransactionsList();
    /**
     * <code>repeated .stratum.Transaction transactions = 1;</code>
     */
    org.smartwallet.stratum.protos.Protos.Transaction getTransactions(int index);
    /**
     * <code>repeated .stratum.Transaction transactions = 1;</code>
     */
    int getTransactionsCount();
    /**
     * <code>repeated .stratum.Transaction transactions = 1;</code>
     */
    java.util.List<? extends org.smartwallet.stratum.protos.Protos.TransactionOrBuilder> 
        getTransactionsOrBuilderList();
    /**
     * <code>repeated .stratum.Transaction transactions = 1;</code>
     */
    org.smartwallet.stratum.protos.Protos.TransactionOrBuilder getTransactionsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code stratum.Electrum}
   */
  public static final class Electrum extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:stratum.Electrum)
      ElectrumOrBuilder {
    // Use Electrum.newBuilder() to construct.
    private Electrum(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Electrum(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Electrum defaultInstance;
    public static Electrum getDefaultInstance() {
      return defaultInstance;
    }

    public Electrum getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Electrum(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                transactions_ = new java.util.ArrayList<org.smartwallet.stratum.protos.Protos.Transaction>();
                mutable_bitField0_ |= 0x00000001;
              }
              transactions_.add(input.readMessage(org.smartwallet.stratum.protos.Protos.Transaction.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          transactions_ = java.util.Collections.unmodifiableList(transactions_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.smartwallet.stratum.protos.Protos.internal_static_stratum_Electrum_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.smartwallet.stratum.protos.Protos.internal_static_stratum_Electrum_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.smartwallet.stratum.protos.Protos.Electrum.class, org.smartwallet.stratum.protos.Protos.Electrum.Builder.class);
    }

    public static com.google.protobuf.Parser<Electrum> PARSER =
        new com.google.protobuf.AbstractParser<Electrum>() {
      public Electrum parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Electrum(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Electrum> getParserForType() {
      return PARSER;
    }

    public static final int TRANSACTIONS_FIELD_NUMBER = 1;
    private java.util.List<org.smartwallet.stratum.protos.Protos.Transaction> transactions_;
    /**
     * <code>repeated .stratum.Transaction transactions = 1;</code>
     */
    public java.util.List<org.smartwallet.stratum.protos.Protos.Transaction> getTransactionsList() {
      return transactions_;
    }
    /**
     * <code>repeated .stratum.Transaction transactions = 1;</code>
     */
    public java.util.List<? extends org.smartwallet.stratum.protos.Protos.TransactionOrBuilder> 
        getTransactionsOrBuilderList() {
      return transactions_;
    }
    /**
     * <code>repeated .stratum.Transaction transactions = 1;</code>
     */
    public int getTransactionsCount() {
      return transactions_.size();
    }
    /**
     * <code>repeated .stratum.Transaction transactions = 1;</code>
     */
    public org.smartwallet.stratum.protos.Protos.Transaction getTransactions(int index) {
      return transactions_.get(index);
    }
    /**
     * <code>repeated .stratum.Transaction transactions = 1;</code>
     */
    public org.smartwallet.stratum.protos.Protos.TransactionOrBuilder getTransactionsOrBuilder(
        int index) {
      return transactions_.get(index);
    }

    private void initFields() {
      transactions_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getTransactionsCount(); i++) {
        if (!getTransactions(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < transactions_.size(); i++) {
        output.writeMessage(1, transactions_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < transactions_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, transactions_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.smartwallet.stratum.protos.Protos.Electrum parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.smartwallet.stratum.protos.Protos.Electrum parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.smartwallet.stratum.protos.Protos.Electrum parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.smartwallet.stratum.protos.Protos.Electrum parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.smartwallet.stratum.protos.Protos.Electrum parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.smartwallet.stratum.protos.Protos.Electrum parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.smartwallet.stratum.protos.Protos.Electrum parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.smartwallet.stratum.protos.Protos.Electrum parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.smartwallet.stratum.protos.Protos.Electrum parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.smartwallet.stratum.protos.Protos.Electrum parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.smartwallet.stratum.protos.Protos.Electrum prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code stratum.Electrum}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:stratum.Electrum)
        org.smartwallet.stratum.protos.Protos.ElectrumOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.smartwallet.stratum.protos.Protos.internal_static_stratum_Electrum_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.smartwallet.stratum.protos.Protos.internal_static_stratum_Electrum_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.smartwallet.stratum.protos.Protos.Electrum.class, org.smartwallet.stratum.protos.Protos.Electrum.Builder.class);
      }

      // Construct using org.smartwallet.stratum.protos.Protos.Electrum.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTransactionsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (transactionsBuilder_ == null) {
          transactions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          transactionsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.smartwallet.stratum.protos.Protos.internal_static_stratum_Electrum_descriptor;
      }

      public org.smartwallet.stratum.protos.Protos.Electrum getDefaultInstanceForType() {
        return org.smartwallet.stratum.protos.Protos.Electrum.getDefaultInstance();
      }

      public org.smartwallet.stratum.protos.Protos.Electrum build() {
        org.smartwallet.stratum.protos.Protos.Electrum result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.smartwallet.stratum.protos.Protos.Electrum buildPartial() {
        org.smartwallet.stratum.protos.Protos.Electrum result = new org.smartwallet.stratum.protos.Protos.Electrum(this);
        int from_bitField0_ = bitField0_;
        if (transactionsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            transactions_ = java.util.Collections.unmodifiableList(transactions_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.transactions_ = transactions_;
        } else {
          result.transactions_ = transactionsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.smartwallet.stratum.protos.Protos.Electrum) {
          return mergeFrom((org.smartwallet.stratum.protos.Protos.Electrum)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.smartwallet.stratum.protos.Protos.Electrum other) {
        if (other == org.smartwallet.stratum.protos.Protos.Electrum.getDefaultInstance()) return this;
        if (transactionsBuilder_ == null) {
          if (!other.transactions_.isEmpty()) {
            if (transactions_.isEmpty()) {
              transactions_ = other.transactions_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTransactionsIsMutable();
              transactions_.addAll(other.transactions_);
            }
            onChanged();
          }
        } else {
          if (!other.transactions_.isEmpty()) {
            if (transactionsBuilder_.isEmpty()) {
              transactionsBuilder_.dispose();
              transactionsBuilder_ = null;
              transactions_ = other.transactions_;
              bitField0_ = (bitField0_ & ~0x00000001);
              transactionsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTransactionsFieldBuilder() : null;
            } else {
              transactionsBuilder_.addAllMessages(other.transactions_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getTransactionsCount(); i++) {
          if (!getTransactions(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.smartwallet.stratum.protos.Protos.Electrum parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.smartwallet.stratum.protos.Protos.Electrum) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<org.smartwallet.stratum.protos.Protos.Transaction> transactions_ =
        java.util.Collections.emptyList();
      private void ensureTransactionsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          transactions_ = new java.util.ArrayList<org.smartwallet.stratum.protos.Protos.Transaction>(transactions_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.smartwallet.stratum.protos.Protos.Transaction, org.smartwallet.stratum.protos.Protos.Transaction.Builder, org.smartwallet.stratum.protos.Protos.TransactionOrBuilder> transactionsBuilder_;

      /**
       * <code>repeated .stratum.Transaction transactions = 1;</code>
       */
      public java.util.List<org.smartwallet.stratum.protos.Protos.Transaction> getTransactionsList() {
        if (transactionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(transactions_);
        } else {
          return transactionsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .stratum.Transaction transactions = 1;</code>
       */
      public int getTransactionsCount() {
        if (transactionsBuilder_ == null) {
          return transactions_.size();
        } else {
          return transactionsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .stratum.Transaction transactions = 1;</code>
       */
      public org.smartwallet.stratum.protos.Protos.Transaction getTransactions(int index) {
        if (transactionsBuilder_ == null) {
          return transactions_.get(index);
        } else {
          return transactionsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .stratum.Transaction transactions = 1;</code>
       */
      public Builder setTransactions(
          int index, org.smartwallet.stratum.protos.Protos.Transaction value) {
        if (transactionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTransactionsIsMutable();
          transactions_.set(index, value);
          onChanged();
        } else {
          transactionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .stratum.Transaction transactions = 1;</code>
       */
      public Builder setTransactions(
          int index, org.smartwallet.stratum.protos.Protos.Transaction.Builder builderForValue) {
        if (transactionsBuilder_ == null) {
          ensureTransactionsIsMutable();
          transactions_.set(index, builderForValue.build());
          onChanged();
        } else {
          transactionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .stratum.Transaction transactions = 1;</code>
       */
      public Builder addTransactions(org.smartwallet.stratum.protos.Protos.Transaction value) {
        if (transactionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTransactionsIsMutable();
          transactions_.add(value);
          onChanged();
        } else {
          transactionsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .stratum.Transaction transactions = 1;</code>
       */
      public Builder addTransactions(
          int index, org.smartwallet.stratum.protos.Protos.Transaction value) {
        if (transactionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTransactionsIsMutable();
          transactions_.add(index, value);
          onChanged();
        } else {
          transactionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .stratum.Transaction transactions = 1;</code>
       */
      public Builder addTransactions(
          org.smartwallet.stratum.protos.Protos.Transaction.Builder builderForValue) {
        if (transactionsBuilder_ == null) {
          ensureTransactionsIsMutable();
          transactions_.add(builderForValue.build());
          onChanged();
        } else {
          transactionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .stratum.Transaction transactions = 1;</code>
       */
      public Builder addTransactions(
          int index, org.smartwallet.stratum.protos.Protos.Transaction.Builder builderForValue) {
        if (transactionsBuilder_ == null) {
          ensureTransactionsIsMutable();
          transactions_.add(index, builderForValue.build());
          onChanged();
        } else {
          transactionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .stratum.Transaction transactions = 1;</code>
       */
      public Builder addAllTransactions(
          java.lang.Iterable<? extends org.smartwallet.stratum.protos.Protos.Transaction> values) {
        if (transactionsBuilder_ == null) {
          ensureTransactionsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, transactions_);
          onChanged();
        } else {
          transactionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .stratum.Transaction transactions = 1;</code>
       */
      public Builder clearTransactions() {
        if (transactionsBuilder_ == null) {
          transactions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          transactionsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .stratum.Transaction transactions = 1;</code>
       */
      public Builder removeTransactions(int index) {
        if (transactionsBuilder_ == null) {
          ensureTransactionsIsMutable();
          transactions_.remove(index);
          onChanged();
        } else {
          transactionsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .stratum.Transaction transactions = 1;</code>
       */
      public org.smartwallet.stratum.protos.Protos.Transaction.Builder getTransactionsBuilder(
          int index) {
        return getTransactionsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .stratum.Transaction transactions = 1;</code>
       */
      public org.smartwallet.stratum.protos.Protos.TransactionOrBuilder getTransactionsOrBuilder(
          int index) {
        if (transactionsBuilder_ == null) {
          return transactions_.get(index);  } else {
          return transactionsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .stratum.Transaction transactions = 1;</code>
       */
      public java.util.List<? extends org.smartwallet.stratum.protos.Protos.TransactionOrBuilder> 
           getTransactionsOrBuilderList() {
        if (transactionsBuilder_ != null) {
          return transactionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(transactions_);
        }
      }
      /**
       * <code>repeated .stratum.Transaction transactions = 1;</code>
       */
      public org.smartwallet.stratum.protos.Protos.Transaction.Builder addTransactionsBuilder() {
        return getTransactionsFieldBuilder().addBuilder(
            org.smartwallet.stratum.protos.Protos.Transaction.getDefaultInstance());
      }
      /**
       * <code>repeated .stratum.Transaction transactions = 1;</code>
       */
      public org.smartwallet.stratum.protos.Protos.Transaction.Builder addTransactionsBuilder(
          int index) {
        return getTransactionsFieldBuilder().addBuilder(
            index, org.smartwallet.stratum.protos.Protos.Transaction.getDefaultInstance());
      }
      /**
       * <code>repeated .stratum.Transaction transactions = 1;</code>
       */
      public java.util.List<org.smartwallet.stratum.protos.Protos.Transaction.Builder> 
           getTransactionsBuilderList() {
        return getTransactionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.smartwallet.stratum.protos.Protos.Transaction, org.smartwallet.stratum.protos.Protos.Transaction.Builder, org.smartwallet.stratum.protos.Protos.TransactionOrBuilder> 
          getTransactionsFieldBuilder() {
        if (transactionsBuilder_ == null) {
          transactionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.smartwallet.stratum.protos.Protos.Transaction, org.smartwallet.stratum.protos.Protos.Transaction.Builder, org.smartwallet.stratum.protos.Protos.TransactionOrBuilder>(
                  transactions_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          transactions_ = null;
        }
        return transactionsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:stratum.Electrum)
    }

    static {
      defaultInstance = new Electrum(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:stratum.Electrum)
  }

  public interface TransactionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:stratum.Transaction)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes transaction = 1;</code>
     *
     * <pre>
     * Bitcoin serialized transaction
     * </pre>
     */
    boolean hasTransaction();
    /**
     * <code>required bytes transaction = 1;</code>
     *
     * <pre>
     * Bitcoin serialized transaction
     * </pre>
     */
    com.google.protobuf.ByteString getTransaction();

    /**
     * <code>required .stratum.TransactionConfidence confidence = 2;</code>
     */
    boolean hasConfidence();
    /**
     * <code>required .stratum.TransactionConfidence confidence = 2;</code>
     */
    org.smartwallet.stratum.protos.Protos.TransactionConfidence getConfidence();
    /**
     * <code>required .stratum.TransactionConfidence confidence = 2;</code>
     */
    org.smartwallet.stratum.protos.Protos.TransactionConfidenceOrBuilder getConfidenceOrBuilder();
  }
  /**
   * Protobuf type {@code stratum.Transaction}
   */
  public static final class Transaction extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:stratum.Transaction)
      TransactionOrBuilder {
    // Use Transaction.newBuilder() to construct.
    private Transaction(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Transaction(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Transaction defaultInstance;
    public static Transaction getDefaultInstance() {
      return defaultInstance;
    }

    public Transaction getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Transaction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              transaction_ = input.readBytes();
              break;
            }
            case 18: {
              org.smartwallet.stratum.protos.Protos.TransactionConfidence.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = confidence_.toBuilder();
              }
              confidence_ = input.readMessage(org.smartwallet.stratum.protos.Protos.TransactionConfidence.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(confidence_);
                confidence_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.smartwallet.stratum.protos.Protos.internal_static_stratum_Transaction_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.smartwallet.stratum.protos.Protos.internal_static_stratum_Transaction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.smartwallet.stratum.protos.Protos.Transaction.class, org.smartwallet.stratum.protos.Protos.Transaction.Builder.class);
    }

    public static com.google.protobuf.Parser<Transaction> PARSER =
        new com.google.protobuf.AbstractParser<Transaction>() {
      public Transaction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Transaction(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Transaction> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TRANSACTION_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString transaction_;
    /**
     * <code>required bytes transaction = 1;</code>
     *
     * <pre>
     * Bitcoin serialized transaction
     * </pre>
     */
    public boolean hasTransaction() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes transaction = 1;</code>
     *
     * <pre>
     * Bitcoin serialized transaction
     * </pre>
     */
    public com.google.protobuf.ByteString getTransaction() {
      return transaction_;
    }

    public static final int CONFIDENCE_FIELD_NUMBER = 2;
    private org.smartwallet.stratum.protos.Protos.TransactionConfidence confidence_;
    /**
     * <code>required .stratum.TransactionConfidence confidence = 2;</code>
     */
    public boolean hasConfidence() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .stratum.TransactionConfidence confidence = 2;</code>
     */
    public org.smartwallet.stratum.protos.Protos.TransactionConfidence getConfidence() {
      return confidence_;
    }
    /**
     * <code>required .stratum.TransactionConfidence confidence = 2;</code>
     */
    public org.smartwallet.stratum.protos.Protos.TransactionConfidenceOrBuilder getConfidenceOrBuilder() {
      return confidence_;
    }

    private void initFields() {
      transaction_ = com.google.protobuf.ByteString.EMPTY;
      confidence_ = org.smartwallet.stratum.protos.Protos.TransactionConfidence.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTransaction()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasConfidence()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, transaction_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, confidence_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, transaction_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, confidence_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.smartwallet.stratum.protos.Protos.Transaction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.smartwallet.stratum.protos.Protos.Transaction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.smartwallet.stratum.protos.Protos.Transaction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.smartwallet.stratum.protos.Protos.Transaction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.smartwallet.stratum.protos.Protos.Transaction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.smartwallet.stratum.protos.Protos.Transaction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.smartwallet.stratum.protos.Protos.Transaction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.smartwallet.stratum.protos.Protos.Transaction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.smartwallet.stratum.protos.Protos.Transaction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.smartwallet.stratum.protos.Protos.Transaction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.smartwallet.stratum.protos.Protos.Transaction prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code stratum.Transaction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:stratum.Transaction)
        org.smartwallet.stratum.protos.Protos.TransactionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.smartwallet.stratum.protos.Protos.internal_static_stratum_Transaction_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.smartwallet.stratum.protos.Protos.internal_static_stratum_Transaction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.smartwallet.stratum.protos.Protos.Transaction.class, org.smartwallet.stratum.protos.Protos.Transaction.Builder.class);
      }

      // Construct using org.smartwallet.stratum.protos.Protos.Transaction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getConfidenceFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        transaction_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (confidenceBuilder_ == null) {
          confidence_ = org.smartwallet.stratum.protos.Protos.TransactionConfidence.getDefaultInstance();
        } else {
          confidenceBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.smartwallet.stratum.protos.Protos.internal_static_stratum_Transaction_descriptor;
      }

      public org.smartwallet.stratum.protos.Protos.Transaction getDefaultInstanceForType() {
        return org.smartwallet.stratum.protos.Protos.Transaction.getDefaultInstance();
      }

      public org.smartwallet.stratum.protos.Protos.Transaction build() {
        org.smartwallet.stratum.protos.Protos.Transaction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.smartwallet.stratum.protos.Protos.Transaction buildPartial() {
        org.smartwallet.stratum.protos.Protos.Transaction result = new org.smartwallet.stratum.protos.Protos.Transaction(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.transaction_ = transaction_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (confidenceBuilder_ == null) {
          result.confidence_ = confidence_;
        } else {
          result.confidence_ = confidenceBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.smartwallet.stratum.protos.Protos.Transaction) {
          return mergeFrom((org.smartwallet.stratum.protos.Protos.Transaction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.smartwallet.stratum.protos.Protos.Transaction other) {
        if (other == org.smartwallet.stratum.protos.Protos.Transaction.getDefaultInstance()) return this;
        if (other.hasTransaction()) {
          setTransaction(other.getTransaction());
        }
        if (other.hasConfidence()) {
          mergeConfidence(other.getConfidence());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTransaction()) {
          
          return false;
        }
        if (!hasConfidence()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.smartwallet.stratum.protos.Protos.Transaction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.smartwallet.stratum.protos.Protos.Transaction) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString transaction_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes transaction = 1;</code>
       *
       * <pre>
       * Bitcoin serialized transaction
       * </pre>
       */
      public boolean hasTransaction() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes transaction = 1;</code>
       *
       * <pre>
       * Bitcoin serialized transaction
       * </pre>
       */
      public com.google.protobuf.ByteString getTransaction() {
        return transaction_;
      }
      /**
       * <code>required bytes transaction = 1;</code>
       *
       * <pre>
       * Bitcoin serialized transaction
       * </pre>
       */
      public Builder setTransaction(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        transaction_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes transaction = 1;</code>
       *
       * <pre>
       * Bitcoin serialized transaction
       * </pre>
       */
      public Builder clearTransaction() {
        bitField0_ = (bitField0_ & ~0x00000001);
        transaction_ = getDefaultInstance().getTransaction();
        onChanged();
        return this;
      }

      private org.smartwallet.stratum.protos.Protos.TransactionConfidence confidence_ = org.smartwallet.stratum.protos.Protos.TransactionConfidence.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.smartwallet.stratum.protos.Protos.TransactionConfidence, org.smartwallet.stratum.protos.Protos.TransactionConfidence.Builder, org.smartwallet.stratum.protos.Protos.TransactionConfidenceOrBuilder> confidenceBuilder_;
      /**
       * <code>required .stratum.TransactionConfidence confidence = 2;</code>
       */
      public boolean hasConfidence() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .stratum.TransactionConfidence confidence = 2;</code>
       */
      public org.smartwallet.stratum.protos.Protos.TransactionConfidence getConfidence() {
        if (confidenceBuilder_ == null) {
          return confidence_;
        } else {
          return confidenceBuilder_.getMessage();
        }
      }
      /**
       * <code>required .stratum.TransactionConfidence confidence = 2;</code>
       */
      public Builder setConfidence(org.smartwallet.stratum.protos.Protos.TransactionConfidence value) {
        if (confidenceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          confidence_ = value;
          onChanged();
        } else {
          confidenceBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .stratum.TransactionConfidence confidence = 2;</code>
       */
      public Builder setConfidence(
          org.smartwallet.stratum.protos.Protos.TransactionConfidence.Builder builderForValue) {
        if (confidenceBuilder_ == null) {
          confidence_ = builderForValue.build();
          onChanged();
        } else {
          confidenceBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .stratum.TransactionConfidence confidence = 2;</code>
       */
      public Builder mergeConfidence(org.smartwallet.stratum.protos.Protos.TransactionConfidence value) {
        if (confidenceBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              confidence_ != org.smartwallet.stratum.protos.Protos.TransactionConfidence.getDefaultInstance()) {
            confidence_ =
              org.smartwallet.stratum.protos.Protos.TransactionConfidence.newBuilder(confidence_).mergeFrom(value).buildPartial();
          } else {
            confidence_ = value;
          }
          onChanged();
        } else {
          confidenceBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .stratum.TransactionConfidence confidence = 2;</code>
       */
      public Builder clearConfidence() {
        if (confidenceBuilder_ == null) {
          confidence_ = org.smartwallet.stratum.protos.Protos.TransactionConfidence.getDefaultInstance();
          onChanged();
        } else {
          confidenceBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .stratum.TransactionConfidence confidence = 2;</code>
       */
      public org.smartwallet.stratum.protos.Protos.TransactionConfidence.Builder getConfidenceBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getConfidenceFieldBuilder().getBuilder();
      }
      /**
       * <code>required .stratum.TransactionConfidence confidence = 2;</code>
       */
      public org.smartwallet.stratum.protos.Protos.TransactionConfidenceOrBuilder getConfidenceOrBuilder() {
        if (confidenceBuilder_ != null) {
          return confidenceBuilder_.getMessageOrBuilder();
        } else {
          return confidence_;
        }
      }
      /**
       * <code>required .stratum.TransactionConfidence confidence = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.smartwallet.stratum.protos.Protos.TransactionConfidence, org.smartwallet.stratum.protos.Protos.TransactionConfidence.Builder, org.smartwallet.stratum.protos.Protos.TransactionConfidenceOrBuilder> 
          getConfidenceFieldBuilder() {
        if (confidenceBuilder_ == null) {
          confidenceBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.smartwallet.stratum.protos.Protos.TransactionConfidence, org.smartwallet.stratum.protos.Protos.TransactionConfidence.Builder, org.smartwallet.stratum.protos.Protos.TransactionConfidenceOrBuilder>(
                  getConfidence(),
                  getParentForChildren(),
                  isClean());
          confidence_ = null;
        }
        return confidenceBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:stratum.Transaction)
    }

    static {
      defaultInstance = new Transaction(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:stratum.Transaction)
  }

  public interface TransactionConfidenceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:stratum.TransactionConfidence)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .stratum.TransactionConfidence.Type type = 1;</code>
     *
     * <pre>
     * This is optional in case we add confidence types to prevent parse errors - backwards compatible.
     * </pre>
     */
    boolean hasType();
    /**
     * <code>optional .stratum.TransactionConfidence.Type type = 1;</code>
     *
     * <pre>
     * This is optional in case we add confidence types to prevent parse errors - backwards compatible.
     * </pre>
     */
    org.smartwallet.stratum.protos.Protos.TransactionConfidence.Type getType();

    /**
     * <code>optional int32 appeared_at_height = 2;</code>
     *
     * <pre>
     * If type == BUILDING then this is the chain height at which the transaction was included.
     * </pre>
     */
    boolean hasAppearedAtHeight();
    /**
     * <code>optional int32 appeared_at_height = 2;</code>
     *
     * <pre>
     * If type == BUILDING then this is the chain height at which the transaction was included.
     * </pre>
     */
    int getAppearedAtHeight();

    /**
     * <code>optional bytes overriding_transaction = 3;</code>
     *
     * <pre>
     * If set, hash of the transaction that double spent this one into oblivion. A transaction can be double spent by
     * multiple transactions in the case of several inputs being re-spent by several transactions but we don't
     * bother to track them all, just the first. This only makes sense if type = DEAD.
     * </pre>
     */
    boolean hasOverridingTransaction();
    /**
     * <code>optional bytes overriding_transaction = 3;</code>
     *
     * <pre>
     * If set, hash of the transaction that double spent this one into oblivion. A transaction can be double spent by
     * multiple transactions in the case of several inputs being re-spent by several transactions but we don't
     * bother to track them all, just the first. This only makes sense if type = DEAD.
     * </pre>
     */
    com.google.protobuf.ByteString getOverridingTransaction();

    /**
     * <code>optional int32 depth = 4;</code>
     *
     * <pre>
     * If type == BUILDING then this is the depth of the transaction in the blockchain.
     * Zero confirmations: depth = 0, one confirmation: depth = 1 etc.
     * </pre>
     */
    boolean hasDepth();
    /**
     * <code>optional int32 depth = 4;</code>
     *
     * <pre>
     * If type == BUILDING then this is the depth of the transaction in the blockchain.
     * Zero confirmations: depth = 0, one confirmation: depth = 1 etc.
     * </pre>
     */
    int getDepth();

    /**
     * <code>optional .stratum.TransactionConfidence.Source source = 7;</code>
     */
    boolean hasSource();
    /**
     * <code>optional .stratum.TransactionConfidence.Source source = 7;</code>
     */
    org.smartwallet.stratum.protos.Protos.TransactionConfidence.Source getSource();
  }
  /**
   * Protobuf type {@code stratum.TransactionConfidence}
   */
  public static final class TransactionConfidence extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:stratum.TransactionConfidence)
      TransactionConfidenceOrBuilder {
    // Use TransactionConfidence.newBuilder() to construct.
    private TransactionConfidence(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TransactionConfidence(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TransactionConfidence defaultInstance;
    public static TransactionConfidence getDefaultInstance() {
      return defaultInstance;
    }

    public TransactionConfidence getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TransactionConfidence(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              org.smartwallet.stratum.protos.Protos.TransactionConfidence.Type value = org.smartwallet.stratum.protos.Protos.TransactionConfidence.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              appearedAtHeight_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              overridingTransaction_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              depth_ = input.readInt32();
              break;
            }
            case 56: {
              int rawValue = input.readEnum();
              org.smartwallet.stratum.protos.Protos.TransactionConfidence.Source value = org.smartwallet.stratum.protos.Protos.TransactionConfidence.Source.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(7, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                source_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.smartwallet.stratum.protos.Protos.internal_static_stratum_TransactionConfidence_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.smartwallet.stratum.protos.Protos.internal_static_stratum_TransactionConfidence_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.smartwallet.stratum.protos.Protos.TransactionConfidence.class, org.smartwallet.stratum.protos.Protos.TransactionConfidence.Builder.class);
    }

    public static com.google.protobuf.Parser<TransactionConfidence> PARSER =
        new com.google.protobuf.AbstractParser<TransactionConfidence>() {
      public TransactionConfidence parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TransactionConfidence(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TransactionConfidence> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code stratum.TransactionConfidence.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0, 0),
      /**
       * <code>BUILDING = 1;</code>
       *
       * <pre>
       * In best chain.  If and only if appeared_at_height is present.
       * </pre>
       */
      BUILDING(1, 1),
      /**
       * <code>PENDING = 2;</code>
       *
       * <pre>
       * Unconfirmed and sitting in the networks memory pools, waiting to be included in the chain.
       * </pre>
       */
      PENDING(2, 2),
      /**
       * <code>NOT_IN_BEST_CHAIN = 3;</code>
       *
       * <pre>
       * Deprecated: equivalent to PENDING.
       * </pre>
       */
      NOT_IN_BEST_CHAIN(3, 3),
      /**
       * <code>DEAD = 4;</code>
       *
       * <pre>
       * Either if overriding_transaction is present or transaction is dead coinbase
       * </pre>
       */
      DEAD(4, 4),
      ;

      /**
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <code>BUILDING = 1;</code>
       *
       * <pre>
       * In best chain.  If and only if appeared_at_height is present.
       * </pre>
       */
      public static final int BUILDING_VALUE = 1;
      /**
       * <code>PENDING = 2;</code>
       *
       * <pre>
       * Unconfirmed and sitting in the networks memory pools, waiting to be included in the chain.
       * </pre>
       */
      public static final int PENDING_VALUE = 2;
      /**
       * <code>NOT_IN_BEST_CHAIN = 3;</code>
       *
       * <pre>
       * Deprecated: equivalent to PENDING.
       * </pre>
       */
      public static final int NOT_IN_BEST_CHAIN_VALUE = 3;
      /**
       * <code>DEAD = 4;</code>
       *
       * <pre>
       * Either if overriding_transaction is present or transaction is dead coinbase
       * </pre>
       */
      public static final int DEAD_VALUE = 4;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 1: return BUILDING;
          case 2: return PENDING;
          case 3: return NOT_IN_BEST_CHAIN;
          case 4: return DEAD;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.smartwallet.stratum.protos.Protos.TransactionConfidence.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:stratum.TransactionConfidence.Type)
    }

    /**
     * Protobuf enum {@code stratum.TransactionConfidence.Source}
     *
     * <pre>
     * Where did we get this transaction from? Knowing the source may help us to risk analyze pending transactions.
     * </pre>
     */
    public enum Source
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SOURCE_UNKNOWN = 0;</code>
       *
       * <pre>
       * We don't know where it came from, or this is a wallet from the future.
       * </pre>
       */
      SOURCE_UNKNOWN(0, 0),
      /**
       * <code>SOURCE_NETWORK = 1;</code>
       *
       * <pre>
       * We received it from a network broadcast. This is the normal way to get payments.
       * </pre>
       */
      SOURCE_NETWORK(1, 1),
      /**
       * <code>SOURCE_SELF = 2;</code>
       *
       * <pre>
       * We made it ourselves, so we know it should be valid.
       * </pre>
       */
      SOURCE_SELF(2, 2),
      ;

      /**
       * <code>SOURCE_UNKNOWN = 0;</code>
       *
       * <pre>
       * We don't know where it came from, or this is a wallet from the future.
       * </pre>
       */
      public static final int SOURCE_UNKNOWN_VALUE = 0;
      /**
       * <code>SOURCE_NETWORK = 1;</code>
       *
       * <pre>
       * We received it from a network broadcast. This is the normal way to get payments.
       * </pre>
       */
      public static final int SOURCE_NETWORK_VALUE = 1;
      /**
       * <code>SOURCE_SELF = 2;</code>
       *
       * <pre>
       * We made it ourselves, so we know it should be valid.
       * </pre>
       */
      public static final int SOURCE_SELF_VALUE = 2;


      public final int getNumber() { return value; }

      public static Source valueOf(int value) {
        switch (value) {
          case 0: return SOURCE_UNKNOWN;
          case 1: return SOURCE_NETWORK;
          case 2: return SOURCE_SELF;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Source>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Source>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Source>() {
              public Source findValueByNumber(int number) {
                return Source.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.smartwallet.stratum.protos.Protos.TransactionConfidence.getDescriptor().getEnumTypes().get(1);
      }

      private static final Source[] VALUES = values();

      public static Source valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Source(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:stratum.TransactionConfidence.Source)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private org.smartwallet.stratum.protos.Protos.TransactionConfidence.Type type_;
    /**
     * <code>optional .stratum.TransactionConfidence.Type type = 1;</code>
     *
     * <pre>
     * This is optional in case we add confidence types to prevent parse errors - backwards compatible.
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .stratum.TransactionConfidence.Type type = 1;</code>
     *
     * <pre>
     * This is optional in case we add confidence types to prevent parse errors - backwards compatible.
     * </pre>
     */
    public org.smartwallet.stratum.protos.Protos.TransactionConfidence.Type getType() {
      return type_;
    }

    public static final int APPEARED_AT_HEIGHT_FIELD_NUMBER = 2;
    private int appearedAtHeight_;
    /**
     * <code>optional int32 appeared_at_height = 2;</code>
     *
     * <pre>
     * If type == BUILDING then this is the chain height at which the transaction was included.
     * </pre>
     */
    public boolean hasAppearedAtHeight() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 appeared_at_height = 2;</code>
     *
     * <pre>
     * If type == BUILDING then this is the chain height at which the transaction was included.
     * </pre>
     */
    public int getAppearedAtHeight() {
      return appearedAtHeight_;
    }

    public static final int OVERRIDING_TRANSACTION_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString overridingTransaction_;
    /**
     * <code>optional bytes overriding_transaction = 3;</code>
     *
     * <pre>
     * If set, hash of the transaction that double spent this one into oblivion. A transaction can be double spent by
     * multiple transactions in the case of several inputs being re-spent by several transactions but we don't
     * bother to track them all, just the first. This only makes sense if type = DEAD.
     * </pre>
     */
    public boolean hasOverridingTransaction() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes overriding_transaction = 3;</code>
     *
     * <pre>
     * If set, hash of the transaction that double spent this one into oblivion. A transaction can be double spent by
     * multiple transactions in the case of several inputs being re-spent by several transactions but we don't
     * bother to track them all, just the first. This only makes sense if type = DEAD.
     * </pre>
     */
    public com.google.protobuf.ByteString getOverridingTransaction() {
      return overridingTransaction_;
    }

    public static final int DEPTH_FIELD_NUMBER = 4;
    private int depth_;
    /**
     * <code>optional int32 depth = 4;</code>
     *
     * <pre>
     * If type == BUILDING then this is the depth of the transaction in the blockchain.
     * Zero confirmations: depth = 0, one confirmation: depth = 1 etc.
     * </pre>
     */
    public boolean hasDepth() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 depth = 4;</code>
     *
     * <pre>
     * If type == BUILDING then this is the depth of the transaction in the blockchain.
     * Zero confirmations: depth = 0, one confirmation: depth = 1 etc.
     * </pre>
     */
    public int getDepth() {
      return depth_;
    }

    public static final int SOURCE_FIELD_NUMBER = 7;
    private org.smartwallet.stratum.protos.Protos.TransactionConfidence.Source source_;
    /**
     * <code>optional .stratum.TransactionConfidence.Source source = 7;</code>
     */
    public boolean hasSource() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .stratum.TransactionConfidence.Source source = 7;</code>
     */
    public org.smartwallet.stratum.protos.Protos.TransactionConfidence.Source getSource() {
      return source_;
    }

    private void initFields() {
      type_ = org.smartwallet.stratum.protos.Protos.TransactionConfidence.Type.UNKNOWN;
      appearedAtHeight_ = 0;
      overridingTransaction_ = com.google.protobuf.ByteString.EMPTY;
      depth_ = 0;
      source_ = org.smartwallet.stratum.protos.Protos.TransactionConfidence.Source.SOURCE_UNKNOWN;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, appearedAtHeight_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, overridingTransaction_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, depth_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(7, source_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, appearedAtHeight_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, overridingTransaction_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, depth_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, source_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.smartwallet.stratum.protos.Protos.TransactionConfidence parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.smartwallet.stratum.protos.Protos.TransactionConfidence parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.smartwallet.stratum.protos.Protos.TransactionConfidence parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.smartwallet.stratum.protos.Protos.TransactionConfidence parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.smartwallet.stratum.protos.Protos.TransactionConfidence parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.smartwallet.stratum.protos.Protos.TransactionConfidence parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.smartwallet.stratum.protos.Protos.TransactionConfidence parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.smartwallet.stratum.protos.Protos.TransactionConfidence parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.smartwallet.stratum.protos.Protos.TransactionConfidence parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.smartwallet.stratum.protos.Protos.TransactionConfidence parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.smartwallet.stratum.protos.Protos.TransactionConfidence prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code stratum.TransactionConfidence}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:stratum.TransactionConfidence)
        org.smartwallet.stratum.protos.Protos.TransactionConfidenceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.smartwallet.stratum.protos.Protos.internal_static_stratum_TransactionConfidence_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.smartwallet.stratum.protos.Protos.internal_static_stratum_TransactionConfidence_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.smartwallet.stratum.protos.Protos.TransactionConfidence.class, org.smartwallet.stratum.protos.Protos.TransactionConfidence.Builder.class);
      }

      // Construct using org.smartwallet.stratum.protos.Protos.TransactionConfidence.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = org.smartwallet.stratum.protos.Protos.TransactionConfidence.Type.UNKNOWN;
        bitField0_ = (bitField0_ & ~0x00000001);
        appearedAtHeight_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        overridingTransaction_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        depth_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        source_ = org.smartwallet.stratum.protos.Protos.TransactionConfidence.Source.SOURCE_UNKNOWN;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.smartwallet.stratum.protos.Protos.internal_static_stratum_TransactionConfidence_descriptor;
      }

      public org.smartwallet.stratum.protos.Protos.TransactionConfidence getDefaultInstanceForType() {
        return org.smartwallet.stratum.protos.Protos.TransactionConfidence.getDefaultInstance();
      }

      public org.smartwallet.stratum.protos.Protos.TransactionConfidence build() {
        org.smartwallet.stratum.protos.Protos.TransactionConfidence result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.smartwallet.stratum.protos.Protos.TransactionConfidence buildPartial() {
        org.smartwallet.stratum.protos.Protos.TransactionConfidence result = new org.smartwallet.stratum.protos.Protos.TransactionConfidence(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.appearedAtHeight_ = appearedAtHeight_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.overridingTransaction_ = overridingTransaction_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.depth_ = depth_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.source_ = source_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.smartwallet.stratum.protos.Protos.TransactionConfidence) {
          return mergeFrom((org.smartwallet.stratum.protos.Protos.TransactionConfidence)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.smartwallet.stratum.protos.Protos.TransactionConfidence other) {
        if (other == org.smartwallet.stratum.protos.Protos.TransactionConfidence.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasAppearedAtHeight()) {
          setAppearedAtHeight(other.getAppearedAtHeight());
        }
        if (other.hasOverridingTransaction()) {
          setOverridingTransaction(other.getOverridingTransaction());
        }
        if (other.hasDepth()) {
          setDepth(other.getDepth());
        }
        if (other.hasSource()) {
          setSource(other.getSource());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.smartwallet.stratum.protos.Protos.TransactionConfidence parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.smartwallet.stratum.protos.Protos.TransactionConfidence) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private org.smartwallet.stratum.protos.Protos.TransactionConfidence.Type type_ = org.smartwallet.stratum.protos.Protos.TransactionConfidence.Type.UNKNOWN;
      /**
       * <code>optional .stratum.TransactionConfidence.Type type = 1;</code>
       *
       * <pre>
       * This is optional in case we add confidence types to prevent parse errors - backwards compatible.
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .stratum.TransactionConfidence.Type type = 1;</code>
       *
       * <pre>
       * This is optional in case we add confidence types to prevent parse errors - backwards compatible.
       * </pre>
       */
      public org.smartwallet.stratum.protos.Protos.TransactionConfidence.Type getType() {
        return type_;
      }
      /**
       * <code>optional .stratum.TransactionConfidence.Type type = 1;</code>
       *
       * <pre>
       * This is optional in case we add confidence types to prevent parse errors - backwards compatible.
       * </pre>
       */
      public Builder setType(org.smartwallet.stratum.protos.Protos.TransactionConfidence.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .stratum.TransactionConfidence.Type type = 1;</code>
       *
       * <pre>
       * This is optional in case we add confidence types to prevent parse errors - backwards compatible.
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = org.smartwallet.stratum.protos.Protos.TransactionConfidence.Type.UNKNOWN;
        onChanged();
        return this;
      }

      private int appearedAtHeight_ ;
      /**
       * <code>optional int32 appeared_at_height = 2;</code>
       *
       * <pre>
       * If type == BUILDING then this is the chain height at which the transaction was included.
       * </pre>
       */
      public boolean hasAppearedAtHeight() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 appeared_at_height = 2;</code>
       *
       * <pre>
       * If type == BUILDING then this is the chain height at which the transaction was included.
       * </pre>
       */
      public int getAppearedAtHeight() {
        return appearedAtHeight_;
      }
      /**
       * <code>optional int32 appeared_at_height = 2;</code>
       *
       * <pre>
       * If type == BUILDING then this is the chain height at which the transaction was included.
       * </pre>
       */
      public Builder setAppearedAtHeight(int value) {
        bitField0_ |= 0x00000002;
        appearedAtHeight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 appeared_at_height = 2;</code>
       *
       * <pre>
       * If type == BUILDING then this is the chain height at which the transaction was included.
       * </pre>
       */
      public Builder clearAppearedAtHeight() {
        bitField0_ = (bitField0_ & ~0x00000002);
        appearedAtHeight_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString overridingTransaction_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes overriding_transaction = 3;</code>
       *
       * <pre>
       * If set, hash of the transaction that double spent this one into oblivion. A transaction can be double spent by
       * multiple transactions in the case of several inputs being re-spent by several transactions but we don't
       * bother to track them all, just the first. This only makes sense if type = DEAD.
       * </pre>
       */
      public boolean hasOverridingTransaction() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes overriding_transaction = 3;</code>
       *
       * <pre>
       * If set, hash of the transaction that double spent this one into oblivion. A transaction can be double spent by
       * multiple transactions in the case of several inputs being re-spent by several transactions but we don't
       * bother to track them all, just the first. This only makes sense if type = DEAD.
       * </pre>
       */
      public com.google.protobuf.ByteString getOverridingTransaction() {
        return overridingTransaction_;
      }
      /**
       * <code>optional bytes overriding_transaction = 3;</code>
       *
       * <pre>
       * If set, hash of the transaction that double spent this one into oblivion. A transaction can be double spent by
       * multiple transactions in the case of several inputs being re-spent by several transactions but we don't
       * bother to track them all, just the first. This only makes sense if type = DEAD.
       * </pre>
       */
      public Builder setOverridingTransaction(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        overridingTransaction_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes overriding_transaction = 3;</code>
       *
       * <pre>
       * If set, hash of the transaction that double spent this one into oblivion. A transaction can be double spent by
       * multiple transactions in the case of several inputs being re-spent by several transactions but we don't
       * bother to track them all, just the first. This only makes sense if type = DEAD.
       * </pre>
       */
      public Builder clearOverridingTransaction() {
        bitField0_ = (bitField0_ & ~0x00000004);
        overridingTransaction_ = getDefaultInstance().getOverridingTransaction();
        onChanged();
        return this;
      }

      private int depth_ ;
      /**
       * <code>optional int32 depth = 4;</code>
       *
       * <pre>
       * If type == BUILDING then this is the depth of the transaction in the blockchain.
       * Zero confirmations: depth = 0, one confirmation: depth = 1 etc.
       * </pre>
       */
      public boolean hasDepth() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 depth = 4;</code>
       *
       * <pre>
       * If type == BUILDING then this is the depth of the transaction in the blockchain.
       * Zero confirmations: depth = 0, one confirmation: depth = 1 etc.
       * </pre>
       */
      public int getDepth() {
        return depth_;
      }
      /**
       * <code>optional int32 depth = 4;</code>
       *
       * <pre>
       * If type == BUILDING then this is the depth of the transaction in the blockchain.
       * Zero confirmations: depth = 0, one confirmation: depth = 1 etc.
       * </pre>
       */
      public Builder setDepth(int value) {
        bitField0_ |= 0x00000008;
        depth_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 depth = 4;</code>
       *
       * <pre>
       * If type == BUILDING then this is the depth of the transaction in the blockchain.
       * Zero confirmations: depth = 0, one confirmation: depth = 1 etc.
       * </pre>
       */
      public Builder clearDepth() {
        bitField0_ = (bitField0_ & ~0x00000008);
        depth_ = 0;
        onChanged();
        return this;
      }

      private org.smartwallet.stratum.protos.Protos.TransactionConfidence.Source source_ = org.smartwallet.stratum.protos.Protos.TransactionConfidence.Source.SOURCE_UNKNOWN;
      /**
       * <code>optional .stratum.TransactionConfidence.Source source = 7;</code>
       */
      public boolean hasSource() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .stratum.TransactionConfidence.Source source = 7;</code>
       */
      public org.smartwallet.stratum.protos.Protos.TransactionConfidence.Source getSource() {
        return source_;
      }
      /**
       * <code>optional .stratum.TransactionConfidence.Source source = 7;</code>
       */
      public Builder setSource(org.smartwallet.stratum.protos.Protos.TransactionConfidence.Source value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        source_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .stratum.TransactionConfidence.Source source = 7;</code>
       */
      public Builder clearSource() {
        bitField0_ = (bitField0_ & ~0x00000010);
        source_ = org.smartwallet.stratum.protos.Protos.TransactionConfidence.Source.SOURCE_UNKNOWN;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:stratum.TransactionConfidence)
    }

    static {
      defaultInstance = new TransactionConfidence(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:stratum.TransactionConfidence)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stratum_Electrum_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_stratum_Electrum_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stratum_Transaction_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_stratum_Transaction_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stratum_TransactionConfidence_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_stratum_TransactionConfidence_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016electrum.proto\022\007stratum\"6\n\010Electrum\022*\n" +
      "\014transactions\030\001 \003(\0132\024.stratum.Transactio" +
      "n\"V\n\013Transaction\022\023\n\013transaction\030\001 \002(\014\0222\n" +
      "\nconfidence\030\002 \002(\0132\036.stratum.TransactionC" +
      "onfidence\"\340\002\n\025TransactionConfidence\0221\n\004t" +
      "ype\030\001 \001(\0162#.stratum.TransactionConfidenc" +
      "e.Type\022\032\n\022appeared_at_height\030\002 \001(\005\022\036\n\026ov" +
      "erriding_transaction\030\003 \001(\014\022\r\n\005depth\030\004 \001(" +
      "\005\0225\n\006source\030\007 \001(\0162%.stratum.TransactionC" +
      "onfidence.Source\"O\n\004Type\022\013\n\007UNKNOWN\020\000\022\014\n",
      "\010BUILDING\020\001\022\013\n\007PENDING\020\002\022\025\n\021NOT_IN_BEST_" +
      "CHAIN\020\003\022\010\n\004DEAD\020\004\"A\n\006Source\022\022\n\016SOURCE_UN" +
      "KNOWN\020\000\022\022\n\016SOURCE_NETWORK\020\001\022\017\n\013SOURCE_SE" +
      "LF\020\002B(\n\036org.smartwallet.stratum.protosB\006" +
      "Protos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_stratum_Electrum_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_stratum_Electrum_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_stratum_Electrum_descriptor,
        new java.lang.String[] { "Transactions", });
    internal_static_stratum_Transaction_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_stratum_Transaction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_stratum_Transaction_descriptor,
        new java.lang.String[] { "Transaction", "Confidence", });
    internal_static_stratum_TransactionConfidence_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_stratum_TransactionConfidence_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_stratum_TransactionConfidence_descriptor,
        new java.lang.String[] { "Type", "AppearedAtHeight", "OverridingTransaction", "Depth", "Source", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
